name: Build and Run Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: |
          cd backend
          docker build -t backend .

      - name: Build Frontend Image
        run: |
          cd frontend
          docker build -t frontend .

      - name: Run Backend Container
        run: |
          docker run -d -p 8084:8084 backend

      - name: Run Frontend Container
        run: |
          docker run -d -p 8501:8501 frontend
